config/routes.rb
TrackAdvisor::Application.routes.draw do
  resources :users
  match "logout"                  => "sessions#destroy",         :as => :logout, :via => :delete
  match "auth/:provider/redirect" => "authentications#redirect", :as => :auth_provider
  match "auth/facebook/callback"  => "authentications#facebook"
  match "auth/twitter/callback"   => "authentications#twitter"

  root :to => "home#index"

  resources :cars do
    resource :mileages, :only => [:new, :create, :index] do
      match ""            => "mileages#index", :via => :get
      match ":id/destroy" => "mileages#destroy", :as => :destroy, :via => :delete
    end
    resources :fuels,    :only => [:new, :create, :destroy, :index]
    resources :services, :only => [:new, :create, :destroy, :index]
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
  include ApplicationHelper
  include ActionView::Helpers::TextHelper
  include Rails.application.routes.url_helpers

  CURRENCY_TYPES = ["USD", "EUR"]

  belongs_to :car, :touch => true

  attr_accessible :company_name, :price, :currency, :description

  after_initialize do
    if new_record?
      self.currency = User.current.setting.currency unless self.currency.present?
    end
  end

  validates :price,    :presence => true, :numericality => { :only_integer => true }
  validates :currency, :presence => true, :inclusion => { :in => Service::CURRENCY_TYPES }

  after_create :post_to_social

  scope :in_eur, where(:currency => "EUR")
  scope :in_usd, where(:currency => "USD")

  def self.to_eur(usd)
    Money.new(usd, "USD").exchange_to("EUR").fractional.round
  end

  def self.to_usd(eur)
    Money.new(eur, "EUR").exchange_to("USD").fractional.round
  end

  def self.total_grouped_by_day(start, param_currency = CURRENCY_TYPES.first)
    services = where(:created_at => start.beginning_of_day..Time.current)
    services = services.group("date(created_at)")
    case_condition = param_currency == "EUR" ? "CASE WHEN currency='EUR' THEN price ELSE price / #{EU_BANK.get_rate('EUR', 'USD')} END" \
      : "CASE WHEN currency='USD' THEN price ELSE price * #{EU_BANK.get_rate('EUR', 'USD')} END"
    services = services.select("date(created_at) as created_at, round(sum(#{case_condition})) as price")
    services.group_by{ |f| f.created_at.to_date }
  end

  protected

  def post_to_social
    post_service_to_social(self)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :check_logged_in, :except => [:index]

  def index
    @car      = Car.find(params[:car_id])
    @services = @car.services.order("id DESC")
  end

  def new
    @service = current_user.cars.find(params[:car_id]).services.build
  end

  def create
    @service = current_user.cars.find(params[:car_id]).services.build(params[:service])
    if @service.save
      flash[:notice] = "New service successfully saved"
      redirect_to car_services_path(@service.car)
    else
      render :new
    end
  end

  def destroy
    service = current_user.cars.find(params[:car_id]).services.find(params[:id])
    if service.destroy
      flash[:notice] = "Service successfully deleted"
    end
    redirect_to :back
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  def error_message_for_service_currency(service)
    error_message_on(service, :price, :html_tag => "span", :css_class => "help-inline pull-right", :prepend_text => "Price ") ||
        error_message_on(service, :currency, :html_tag => "span", :css_class => "help-inline pull-right", :prepend_text => "Currency ")
  end

  def services_chart_data(car, currency)
    service_prices_by_day = car.services.total_grouped_by_day(1.month.ago, currency)
    data = service_prices_by_day.map do |k, service|
      {
          :created_at => k,
          :price      => service.first.try(:price) || 0,
      }
    end
    data.to_json
  end
end

app/views/services/_form.haml
.span6.offset3.well
  = form_for @service, :url => car_services_path(@service.car), :method => :post, :class => "form-horizontal" do |f|
    %fieldset
      %legend= "New service for #{@service.car.name}"

      %div{ :class => "control-group#{error_message_for_service_currency(@service).present? ? ' error' : ''}" }
        %label.control-label Total price (currency / value)
        .controls
          .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
            - Service::CURRENCY_TYPES.each do |currency|
              %button{ :type => "button",  :class => "btn btn-info btn-radio" }= currency
              = f.radio_button(:currency, currency, :class => "elem-radio", :style => "display:none;")
          = f.text_field :price, :placeholder => "0"
          = error_message_for_service_currency(@service)

      %div{ :class => "control-group#{f.error_message_on(:company_name).present? ? 'error' : ''}" }
        %label.control-label
          Service name
          %i (optional)
        .controls
          = f.text_field :company_name, :class => "span6", :placeholder => "Porshe Auto Service, USA"
          = f.error_message_on(:company_name, :html_tag => "span", :css_class => "help-inline pull-right")

      %div{ :class => "control-group#{f.error_message_on(:description).present? ? ' error' : ''}" }
        = f.label :description, :class => "control-label" do
          Description
          %i (optional)
        .controls
          = f.text_area :description, :class => "span6", :rows => 5, :placeholder => " ..."
          = f.error_message_on(:description, :html_tag => "span", :css_class => "help-inline pull-right")

    .actions
      %button{ :type => "submit", :class => "btn btn-large btn-success btn-block" }
        %i.icon-ok
        SAVE
      = link_to :back, :class => "btn btn-large btn-block" do
        %i.icon-hand-left
        BACK

app/views/services/_nav.haml
.subnav.well
  .subnav-inner
    - unless @car.nil?
      = link_to car_path(@car), :class => "sb text embossed", :style => "padding-left:14px;" do
        %i.icon-hand-left
        Back to car
      - if @car.user == current_user
        = link_to new_car_service_path(@car), :class => "sb text embossed light-blue", :style => "padding-left:14px;" do
          %i.icon-wrench
          New Service

app/views/services/_service.haml
%tr
  %td= "#{time_ago_in_words(service.created_at)} ago"
  %td= service.company_name
  %td= "~ #{pluralize(service.price, service.currency)}"
  - if logged_in? && current_user.cars.include?(@car)
    %td
      .pull-right
        = link_to car_service_path(@car, service), :class => "btn btn-small btn-danger pull-right", :method => :delete, "data-confirm" => "Are you sure?" do
          Delete

app/views/services/index.haml
= render "nav"
#services-container
  %h3= "#{pluralize(@services.count, 'Service')} for #{@car.name}"
  - unless @services.empty?
    .span12
      .pull-right{ :style => "margin-right: 25px;" }
        %strong Convert to:
        .btn-group{ "data-toggle" => "buttons-radio" }
          = link_to reverted_current_currency, "#{car_services_path(@car)}?currency=#{reverted_current_currency}", :class => "btn btn-info btn-radio"
      #annual
      #services-chart{ :data => { :services =>  services_chart_data(@car, current_currency), :currency => current_currency } }
    %table.table.table-stripped
      %thead.well
        %tr
          %th When?
          %th Where?
          %th Total Price
          - if @car.user == current_user
            %th
      %tbody= render @services

app/views/services/new.haml
#new-service-form-container
  = render "form"