config/routes.rb
TrackAdvisor::Application.routes.draw do
  resources :users
  match "logout"                  => "sessions#destroy",         :as => :logout, :via => :delete
  match "auth/:provider/redirect" => "authentications#redirect", :as => :auth_provider
  match "auth/facebook/callback"  => "authentications#facebook"
  match "auth/twitter/callback"   => "authentications#twitter"

  root :to => "home#index"

  resources :cars do
    resource :mileages, :only => [:new, :create, :index] do
      match ""            => "mileages#index", :via => :get
      match ":id/destroy" => "mileages#destroy", :as => :destroy, :via => :delete
    end
    resources :fuels,    :only => [:new, :create, :destroy, :index]
    resources :services, :only => [:new, :create, :destroy, :index]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username, :use => :slugged

  include Authentication

  has_many :providers
  has_many :cars
  has_one  :setting

  attr_accessible :username, :email, :name, :setting_attributes
  accepts_nested_attributes_for :setting

  validates :email,    :presence => true, :uniqueness => { :case_sensitive => false }
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }

  before_create :build_setting

  def facebook_client
    return @facebook_client unless @facebook_client.nil?
    unless (user_facebook = facebook).nil?
      @facebook_client = Koala::Facebook::API.new(user_facebook.token)
    end
  end

  def twitter_client
    return @twitter_client unless @twitter_client.nil?
    unless (user_twitter = twitter).nil?
      @twitter_client = Twitter::Client.new(
        :oauth_token        => user_twitter.token,
        :oauth_token_secret => user_twitter.token_secret
      )
    end
  end

  def post_to_twitter(message)
    twitter_client.update(message) unless twitter_client.nil?
  end

  def post_to_facebook(message)
    facebook_client.put_connections("me", "feed", :message => message) unless facebook_client.nil?
  end

  def facebook
    providers.find_by_name("facebook")
  end

  def twitter
    providers.find_by_name("twitter")
  end

  def self.current
    UserSession.find.user
  end

  protected

  @facebook_client = nil
  @twitter_client  = nil
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_logged_in

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Your profile successfully updated"
      redirect_to edit_user_path(current_user)
    else
      render :edit
    end
  end
end

app/views/users/_form.haml
.span6.offset3.well
  = form_for @user, :url => user_path(@user), :method => :put, :class => "form-horizontal" do |f|
    %fieldset
      %legend Account Details
      %div{ :class => "control-group#{f.error_message_on(:username).present? ? ' error' : ''}" }
        = f.label :username, :class => "control-label"
        .controls
          = f.text_field :username, :class => "span6"
          = f.error_message_on(:username, :html_tag => "span", :css_class => "help-inline pull-right")

      %div{ :class => "control-group#{f.error_message_on(:name).present? ? ' error' : ''}" }
        = f.label :name, :class => "control-label"
        .controls
          = f.text_field :name, :class => "span6"
          = f.error_message_on(:name, :html_tag => "span", :css_class => "help-inline pull-right")

      = f.fields_for :setting, @user.setting do |setting|
        %legend Service Settings

        %div.row-fluid{ :class => "control-group" }
          %label.control-label.pull-left
            Default Unit (for fueling)
          .controls.pull-right
            .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
              - Fuel::UNIT_TYPES.each do |unit|
                %button{ :type => "button",  :class => "btn btn-info btn-radio" }= unit
                = setting.radio_button(:unit, unit, :class => "elem-radio", :style => "display:none;")

        %div.row-fluid{ :class => "control-group" }
          %label.control-label.pull-left
            Default Currency (for fueling and services)
          .controls.pull-right
            .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
              - Fuel::CURRENCY_TYPES.each do |currency|
                %button{ :type => "button",  :class => "btn btn-info btn-radio" }= currency
                = setting.radio_button(:currency, currency, :class => "elem-radio", :style => "display:none;")

        %div.row-fluid{ :class => "control-group" }
          %label.control-label.pull-left
            Default Mileage Unit (for mileage)
          .controls.pull-right
            .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
              - Mileage::UNIT_TYPES.each do |distance_unit|
                %button{ :type => "button",  :class => "btn btn-info btn-radio" }= distance_unit
                = setting.radio_button(:distance, distance_unit, :class => "elem-radio", :style => "display:none;")

        %legend Social connections
        - facebook_con = current_user.facebook
        .pull-left
          = link_to facebook_con.nil? ? auth_provider_path(:facebook) : "javascript:void(0)", :class => "sb circle large text embossed facebook#{facebook_con.nil? ? '' : ' gray'}" do
            = facebook_con.nil? ? "Add Facebook" : "Facebook added"
        - twitter_con = current_user.twitter
        .pull-right
          = link_to twitter_con.nil? ? auth_provider_path(:twitter) : "javascript:void(0)", :class => "sb circle large text embossed twitter#{twitter_con.nil? ? '' : ' gray'}" do
            = twitter_con.nil? ? "Add Twitter" : "Twitter added"

        %legend Social settings
        - unless facebook_con.nil?
          %div.row-fluid{ :class => "control-group" }
            %label.control-label.pull-left Will post to Facebook?
            .controls.pull-right
              .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
                - ["YES", "NO"].each do |val|
                  %button{ :type => "button",  :class => "btn btn-info btn-radio" }= val
                  = setting.radio_button(:post_to_facebook, val, :class => "elem-radio", :style => "display:none;")
        - unless twitter_con.nil?
          %div.row-fluid{ :class => "control-group" }
            %label.control-label.pull-left Will post to Twitter?
            .controls.pull-right
              .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
                - ["YES", "NO"].each do |val|
                  %button{ :type => "button",  :class => "btn btn-info btn-radio" }= val
                  = setting.radio_button(:post_to_twitter, val, :class => "elem-radio", :style => "display:none;")
    .actions
      %button{ :type => "submit", :class => "btn btn-large btn-success btn-block" }
        %i.icon-ok
        UPDATE
      = link_to :back, :class => "btn btn-large btn-block" do
        %i.icon-hand-left
        BACK

app/views/users/edit.haml
#edit-profile-form-container
  = render "form"