config/routes.rb
TrackAdvisor::Application.routes.draw do
  resources :users
  match "logout"                  => "sessions#destroy",         :as => :logout, :via => :delete
  match "auth/:provider/redirect" => "authentications#redirect", :as => :auth_provider
  match "auth/facebook/callback"  => "authentications#facebook"
  match "auth/twitter/callback"   => "authentications#twitter"

  root :to => "home#index"

  resources :cars do
    resource :mileages, :only => [:new, :create, :index] do
      match ""            => "mileages#index", :via => :get
      match ":id/destroy" => "mileages#destroy", :as => :destroy, :via => :delete
    end
    resources :fuels,    :only => [:new, :create, :destroy, :index]
    resources :services, :only => [:new, :create, :destroy, :index]
  end
end

app/views/shared/_header.haml
#brand
  = link_to root_path do
    TrackAdvisor.co
    %br/
    %span.label.label-info
      It's a service for tracking your car
.navbar
  .navbar-inner
    - unless logged_in?
      .providers.row.pull-right
        = link_to "Login with Facebook", auth_provider_path(:facebook), :class => "sb circle large text embossed facebook"
        = link_to "Login with Twitter", auth_provider_path(:twitter), :class => "sb circle large text embossed twitter"
    - else
      .user-buttons
        .pull-left
          = link_to new_car_path, :class => "sb text embossed", :style => "padding-left:14px;" do
            %i.icon-plus
            Add Car
          - if current_user.cars.count > 0
            = link_to cars_path, :class => "sb text embossed", :style => "padding-left:14px;" do
              - cars_count = current_user.cars.count
              - if cars_count > 1
                %i.icon-list
                = "My #{pluralize(cars_count, 'car')}"
              - else
                %i.icon-eye-open
                My car
        .pull-right
          = link_to edit_user_path(current_user), :class => "sb text embossed", :style => "padding-left:14px;" do
            %i.icon-user
          = link_to "Log Out", logout_path, :id => "btn-logout", :class => "btn btn-danger btn-small", "data-confirm" => "Are you sure?", "data-method" => :delete, :style => "margin-top:-5px;"