config/routes.rb
TrackAdvisor::Application.routes.draw do
  resources :users
  match "logout"                  => "sessions#destroy",         :as => :logout, :via => :delete
  match "auth/:provider/redirect" => "authentications#redirect", :as => :auth_provider
  match "auth/facebook/callback"  => "authentications#facebook"
  match "auth/twitter/callback"   => "authentications#twitter"

  root :to => "home#index"

  resources :cars do
    resource :mileages, :only => [:new, :create, :index] do
      match ""            => "mileages#index", :via => :get
      match ":id/destroy" => "mileages#destroy", :as => :destroy, :via => :delete
    end
    resources :fuels,    :only => [:new, :create, :destroy, :index]
    resources :services, :only => [:new, :create, :destroy, :index]
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  include ApplicationHelper
  include Rails.application.routes.url_helpers

  extend FriendlyId
  friendly_id :name, :use => :slugged

  FUEL_TYPES = ["Petrol", "Diesel", "Petrol + Gas (LPG)", "Petrol + Gas (CNG)", "Gas (LPG)", "Gas (CNG)", "Hybrid", "Ethanol"]

  belongs_to :user
  has_many   :mileages
  has_many   :fuels
  has_many   :services

  attr_accessible :name, :year, :description, :engine_capacity, :engine_power, :engine_fuel, :mileages_attributes, :fuels_attributes, :services_attributes
  accepts_nested_attributes_for :mileages, :reject_if => Proc.new{ |attr| attr[:value].blank? }
  accepts_nested_attributes_for :fuels,    :reject_if => Proc.new{ |attr| attr[:value].blank? && attr[:price].blank? }
  accepts_nested_attributes_for :services, :reject_if => Proc.new{ |attr| attr[:value].blank? && attr[:price].blank? }

  validates :name, :presence => true
  validates :year, :presence => true, :date => { :after => Proc.new{ Time.now - 60.years } }
  validates :engine_fuel,  :presence => true, :inclusion => Car::FUEL_TYPES

  after_create :post_to_social

  def engine
    output =  engine_capacity.present? ? engine_capacity : ""
    output += output.present? ? ", #{engine_fuel}" : engine_fuel   if engine_fuel.present?
    output += output.present? ? ", #{engine_power}" : engine_power if engine_power.present?
    output
  end

  def current_mileage(as_object = false)
    if (last_mileage = mileages.last).nil?
      as_object ? nil : ""
    else
      as_object ? last_mileage : "#{last_mileage.value} #{last_mileage.unit}"
    end
  end

  def last_fuel(as_object = false)
    if (last_fuel = fuels.last).nil?
      as_object ? nil : ""
    else
      as_object ? last_fuel : "#{last_fuel.value} #{last_fuel.unit} (#{last_fuel.price last_fuel.currency})"
    end
  end

  def last_service(as_object = false)
    if (last_service = services.last).nil?
      as_object ? nil : ""
    else
      as_object ? last_service : "#{last_service.price last_service.currency}"
    end
  end

  def total_fuels(unit_of_volume)
    if unit_of_volume == "Liter"
      fuels.in_liters.sum(&:value) + Fuel.to_liters(fuels.in_gallons.sum(&:value))
    else
      fuels.in_gallons.sum(&:value) + Fuel.to_gallons(fuels.in_liters.sum(&:value))
    end
  end

  def total_mileages(distance_unit)
    last_mileage = mileages.last
    first_mileage = mileages.first
    return 0 if last_mileage.nil? || first_mileage.nil?
    if distance_unit == "KM"
      (last_mileage.unit == "KM" ? last_mileage.value : Mileage.to_kms(last_mileage.value)) - (first_mileage.unit == "KM" ? first_mileage.value : Mileage.to_kms(first_mileage.value))
    else
      (last_mileage.unit == "Mile" ? last_mileage.value : Mileage.to_miles(last_mileage.value)) - (first_mileage.unit == "Mile" ? first_mileage.value : Mileage.to_miles(first_mileage.value))
    end
  end

  def total_services(currency)
    if currency == "EUR"
      services.in_eur.sum(&:price) + Service.to_eur(services.in_usd.sum(&:price))
    else
      services.in_usd.sum(&:price) + Service.to_usd(services.in_eur.sum(&:price))
    end
  end

  def owner_setting(name)
    user.setting.send(name)
  end

  def total_price_grouped_by_day(start, param_currency = Fuel::CURRENCY_TYPES.first)
    car_fuels    = fuels.total_price_grouped_by_day(start, param_currency)
    car_services = services.total_grouped_by_day(start, param_currency)

    car_fuels.map do |k, fuel|
      unless car_services[k].nil?
        car_fuels[k].first.price += car_services[k].first.price
        car_services.delete(k)
      end
    end

    car_services.map do |k, service|
      car_fuels[k] = service
    end

    car_fuels
  end

  protected

  def post_to_social
    post_car_to_social(self)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_filter :check_logged_in, :except => [:show]

  def new
    @car     = current_user.cars.build
    @mileage = @car.mileages.build if @car.current_mileage(true).nil?
    @fuel    = @car.fuels.build    if @car.last_fuel(true).nil?
    @service = @car.services.build if @car.last_service(true).nil?
  end

  def create
    @car = current_user.cars.build(params[:car])

    if @car.save
      flash[:notice] = "New car successfully saved."
      redirect_to car_path(@car)
    else
      @mileage = @car.current_mileage(true).nil? ? @car.mileages.build : @car.current_mileage(true)
      @fuel    = @car.last_fuel(true).nil? ? @car.fuels.build : @car.last_fuel(true)
      @service = @car.last_service(true).nil? ? @car.services.build : @car.last_service(true)
      render :new
    end
  end

  def edit
    @car = current_user.cars.find(params[:id])
    @mileage = @car.current_mileage(true).nil? ? @car.mileages.build : @car.current_mileage(true)
    @fuel    = @car.last_fuel(true).nil? ? @car.fuels.build : @car.last_fuel(true)
    @service = @car.last_service(true).nil? ? @car.services.build : @car.last_service(true)
  end

  def update
    @car = current_user.cars.find(params[:id])
    params[:car].delete(:mileages_attributes)

    if @car.update_attributes(params[:car])
      flash[:notice] = "Car successfully updated."
      redirect_to car_path(@car)
    else
      @mileage = @car.current_mileage(true).nil? ? @car.mileages.build : @car.current_mileage(true)
      @fuel    = @car.last_fuel(true).nil? ? @car.last_fuel.build : @car.last_fuel(true)
      @service = @car.last_service(true).nil? ? @car.last_service.build : @car.last_service(true)
      render :edit
    end
  end

  def destroy
    car = current_user.cars.find(params[:id])
    if car.destroy
      flash[:notice] = "Car successfully deleted."
    end
    redirect_to cars_path
  end

  def index
    if current_user.cars.count == 1
      @car = current_user.cars.first
      render :show
    else
      @cars = current_user.cars.all
    end
  end

  def show
    @car = Car.find(params[:id])
  end
end

app/helpers/cars_helper.rb
module CarsHelper
  def error_message_for_engine(car)
    error_message_on(car, :engine_power, :html_tag => "span", :css_class => "help-inline pull-right", :prepend_text => "Power ") ||
        error_message_on(car, :engine_fuel, :html_tag => "span", :css_class => "help-inline", :prepend_text => "Fuel ")
  end

  def total_fuels(car, unit)
    param_unit = Fuel::UNIT_TYPES.include?(unit)  ? unit : Fuel::UNIT_TYPES.first
    pluralize(car.total_fuels(param_unit), param_unit)
  end

  def total_services(car, currency)
    param_currency = Service::CURRENCY_TYPES.include?(currency)  ? currency : Service::CURRENCY_TYPES.first
    pluralize(car.total_services(param_currency), param_currency)
  end

  def total_mileages(car, distance)
    param_distance = Mileage::UNIT_TYPES.include?(distance) ? distance : Mileage::UNIT_TYPES.first
    pluralize(car.total_mileages(param_distance), param_distance)
  end

  def current_unit
    if params[:unit].present? && Fuel::UNIT_TYPES.include?(params[:unit])
      params[:unit]
    else
      logged_in? ? current_user.setting.unit : Fuel::UNIT_TYPES.first
    end
  end

  def current_currency
    if params[:currency].present? && Fuel::CURRENCY_TYPES.include?(params[:currency])
      params[:currency]
    else
      logged_in? ? current_user.setting.currency : Fuel::CURRENCY_TYPES.first
    end
  end

  def current_distance
    if params[:distance].present? && Mileage::UNIT_TYPES.include?(params[:distance])
      params[:distance]
    else
      logged_in? ? current_user.setting.distance : Mileage::UNIT_TYPES.first
    end
  end

  def reverted_current_unit
    unit_types = Fuel::UNIT_TYPES
    unit_types.reject{ |el|el==current_unit }.first
  end

  def reverted_current_currency
    currency_types = Fuel::CURRENCY_TYPES
    currency_types.reject{ |el|el==current_currency }.first
  end

  def reverted_current_distance
    distance_types = Mileage::UNIT_TYPES
    distance_types.reject{ |el|el==current_distance }.first
  end

  def car_chart_data(car, currency)
    car_prices_by_day     = car.total_price_grouped_by_day(1.month.ago, currency)
    fuel_prices_by_day    = car.fuels.total_price_grouped_by_day(1.month.ago, currency)
    service_prices_by_day = car.services.total_grouped_by_day(1.month.ago, currency)

    data = car_prices_by_day.map do |k, node|
      {
          :created_at    => k,
          :total_price   => node.first.try(:price) || 0,
          :fuel_price    => fuel_prices_by_day[k].nil? ? 0 : fuel_prices_by_day[k].first.try(:price),
          :service_price => service_prices_by_day[k].nil? ? 0 : service_prices_by_day[k].first.try(:price)
      }
    end
    data.to_json
  end
end

app/views/cars/_car.haml
%tr
  %th
    = link_to car.name, car_path(car)
  %th= car.engine
  %td
    .pull-right
      .btn-group
        = link_to new_car_fuel_path(car), :class => "btn btn-small btn-success" do
          New Fueling
        = link_to new_car_service_path(car), :class => "btn btn-small" do
          New Service
        = link_to new_car_mileages_path(car), :class => "btn btn-small btn-success" do
          New Mileage

app/views/cars/_form.haml
.span6.offset3.well
  = form_for @car, :class => "form-horizontal" do |f|
    %fieldset
      %legend
        Car Details
        - unless @car.new_record?
          .pull-right
            = link_to "Delete", car_path(@car), :method => :delete, :class => "btn btn-danger btn-small", "data-confirm" => "Are you sure?", :style => "margin-top:-9px;"

      %div{ :class => "control-group#{f.error_message_on(:name).present? ? ' error' : ''}" }
        = f.label :name, :class => "control-label"
        .controls
          = f.text_field :name, :class => "span6", :placeholder => "Porsche Panamera GTS"
          = f.error_message_on(:name, :html_tag => "span", :css_class => "help-inline pull-right")

      %div{ :class => "control-group#{f.error_message_on(:year).present? ? ' error' : ''}" }
        = f.label :year, :class => "control-label"
        .controls
          = select_year(@car.year || Date.today, :start_year => Time.now.year, :end_year => Time.now.year - 60, :field_name => "year", :prefix => "car")
          = f.error_message_on(:year, :html_tag => "span", :css_class => "help-inline")

      %div{ :class => "control-group#{error_message_for_engine(@car).present? ? ' error' : ''}" }
        %label.control-label Engine (capacity / fuel / power)
        .controls
          = f.text_field :engine_capacity, :placeholder => "4.8 V8"
          = f.select :engine_fuel, Car::FUEL_TYPES
          = f.text_field :engine_power, :placeholder => "316 kW"
          = error_message_for_engine(@car)

      %div{ :class => "control-group#{f.error_message_on(:description).present? ? ' error' : ''}" }
        = f.label :description, :class => "control-label" do
          Description
          %i (optional)
        .controls
          = f.text_area :description, :class => "span6", :rows => 5, :placeholder => " ..."
          = f.error_message_on(:description, :html_tag => "span", :css_class => "help-inline pull-right")

      %legend
        Current Mileage
        - if @car.new_record?
          %i (optional)
      - unless @car.new_record?
        .pull-right
          = link_to "New", new_car_mileages_path(@car), :class => "btn btn-small", :style => "margin-top:-9px;"
          - unless @mileage.new_record?
            = link_to "Delete", destroy_car_mileages_path(@car, @mileage), :method => :delete, :class => "btn btn-danger btn-small", "data-confirm" => "Are you sure?", :style => "margin-top:-9px;"
      = f.fields_for :mileages, @mileage do |m|
        %div{ :class => "control-group#{error_message_for_mileage(@mileage).present? ? ' error' : ''}" }
          %label.control-label Current Mileage (unit / value)
          .controls
            .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
              - Mileage::UNIT_TYPES.each do |unit|
                %button{ :type => "button", :class => "btn btn-info btn-radio", :disabled => @car.new_record? || unit == @mileage.unit ? false : true }= unit
                = m.radio_button(:unit, unit, :class => "elem-radio", :style => "display:none;", :disabled => @car.new_record? ? false : true)
            = m.text_field :value, :placeholder => "0", :class => "mileage_unit_value_attribute", :disabled => @car.new_record? ? false : true

            -#= m.select :unit, Mileage::UNIT_TYPES, {}, { :class => "car_mileages_attributes", :disabled => @car.new_record? ? false : true }
            - if @car.new_record?
              = error_message_for_mileage(@mileage)

      %legend
        Last Fueling
        - if @car.new_record?
          %i (optional)
      - unless @car.new_record?
        .pull-right
          = link_to "New", new_car_fuel_path(@car), :class => "btn btn-small", :style => "margin-top:-9px;"
          - unless @fuel.new_record?
            = link_to "Delete", car_fuel_path(@car, @fuel), :method => :delete, :class => "btn btn-danger btn-small", "data-confirm" => "Are you sure?", :style => "margin-top:-9px;"
      = f.fields_for :fuels, @fuel do |fl|
        %div{ :class => "control-group#{error_message_for_fuel_unit(@fuel).present? ? ' error' : ''}" }
          %label.control-label Fueling (unit / value)
          .controls
            .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
              - Fuel::UNIT_TYPES.each do |unit|
                %button{ :type => "button",  :class => "btn btn-info btn-radio", :disabled => @car.new_record? || unit == @fuel.unit ? false : true }= unit
                = fl.radio_button(:unit, unit, :class => "elem-radio", :style => "display:none;", :disabled => @car.new_record? ? false : true)
            = fl.text_field :value, :placeholder => "0", :class => "fuel_unit_value_attribute", :disabled => @car.new_record? ? false : true
            - if @car.new_record?
              = error_message_for_fuel_unit(@fuel)

        %div{ :class => "control-group#{error_message_for_fuel_currency(@fuel).present? ? ' error' : ''}" }
          %label.control-label
            = @car.new_record? ? "Price Per Unit" : "Total Price"
            (currency / value)
          .controls
            .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
              - Fuel::CURRENCY_TYPES.each do |currency|
                %button{ :type => "button",  :class => "btn btn-info btn-radio", :disabled => @car.new_record? || currency == @fuel.currency ? false : true }= currency
                = fl.radio_button(:currency, currency, :class => "elem-radio", :style => "display:none;", :disabled => @car.new_record? ? false : true)
            = fl.text_field (@car.new_record? ? :price_per_unit : :price), :placeholder => "0", :class => "fuel_currency_value_attribute", :disabled => @car.new_record? ? false : true
            - if @car.new_record?
              = error_message_for_fuel_currency(@fuel)

      %legend
        Last Service
        - if @car.new_record?
          %i (optional)
      - unless @car.new_record?
        .pull-right
          = link_to "New", new_car_service_path(@car), :class => "btn btn-small", :style => "margin-top:-9px;"
          - unless @service.new_record?
            = link_to "Delete", car_service_path(@car, @service), :method => :delete, :class => "btn btn-danger btn-small", "data-confirm" => "Are you sure?", :style => "margin-top:-9px;"
      = f.fields_for :services, @service do |sv|
        %div{ :class => "control-group#{error_message_for_service_currency(@service).present? ? ' error' : ''}" }
          %label.control-label Total Price (currency / value)
          .controls
            .btn-group{ "data-toggle" => "buttons-radio", :style => "margin-top:-10px;" }
              - Service::CURRENCY_TYPES.each do |currency|
                %button{ :type => "button",  :class => "btn btn-info btn-radio", :disabled => @car.new_record? || currency == @service.currency ? false : true }= currency
                = sv.radio_button(:currency, currency, :class => "elem-radio", :style => "display:none;", :disabled => @car.new_record? ? false : true)
            = sv.text_field :price, :placeholder => "0", :class => "fuel_currency_value_attribute", :disabled => @car.new_record? ? false : true
            - if @car.new_record?
              = error_message_for_fuel_currency(@service)

        %div{ :class => "control-group#{sv.error_message_on(:company_name).present? ? 'error' : ''}" }
          %label.control-label
            Service name
            %i (optional)
          .controls
            = sv.text_field :company_name, :class => "span6", :placeholder => "Porshe Auto Service, USA", :disabled => @car.new_record? ? false : true
            - if @car.new_record?
              = sv.error_message_on(:company_name, :html_tag => "span", :css_class => "help-inline pull-right")

        %div{ :class => "control-group#{sv.error_message_on(:description).present? ? ' error' : ''}" }
          = sv.label :description, :class => "control-label" do
            Description
            %i (optional)
          .controls
            = sv.text_area :description, :class => "span6", :rows => 5, :placeholder => " ...", :disabled => @car.new_record? ? false : true
            - if @car.new_record?
              = sv.error_message_on(:description, :html_tag => "span", :css_class => "help-inline pull-right")

    .actions
      %button{ :type => "submit", :class => "btn btn-large btn-success btn-block" }
        %i.icon-ok
        = @car.new_record? ? "SAVE" : "UPDATE"
      = link_to :back, :class => "btn btn-large btn-block" do
        %i.icon-hand-left
        BACK

app/views/cars/_nav.haml
.subnav
  .subnav-inner
    - unless @car.nil?
      = link_to :back, :class => "sb text embossed", :style => "padding-left:14px;" do
        %i.icon-hand-left
        Back
      - if @car.user == current_user
        = link_to edit_car_path(@car), :class => "sb text embossed", :style => "padding-left:14px" do
          %i.icon-pencil
          Edit

app/views/cars/edit.haml
#edit-car-form-container
  = render "form"

app/views/cars/index.haml
#cars-container
  %h3= pluralize(@cars.count, 'Car')
  - unless @cars.empty?
    %table.table.table-stripped
      %thead.well
        %tr
          %th Name
          %th Engine
          %th
      %tbody= render @cars

app/views/cars/new.haml
#new-car-form-container
  = render "form"

app/views/cars/show.haml
= render "nav"
#car-container
  .row-fluid
    .pull-right
      .row.well{ :style => "text-align:center;" }
        .row-fluid
          .span4
            %h3= total_fuels(@car, logged_in? ? current_user.setting.unit : Fuel::UNIT_TYPES.first)
          .span4
            %h3= total_services(@car, logged_in? ? current_user.setting.currency : Fuel::CURRENCY_TYPES.first)
          .span4
            %h3= total_mileages(@car, logged_in? ? current_user.setting.distance : Mileage::UNIT_TYPES.first)
        .row-fluid
          .span4
            = link_to car_fuels_path(@car), :class => "sb text embossed", :style => "padding-left:14px;" do
              %i.icon-fire
              = "Fuelings (#{@car.fuels.count})"
          .span4
            = link_to car_services_path(@car), :class => "sb text embossed", :style => "padding-left:14px;" do
              %i.icon-wrench
              = "Services (#{@car.services.count})"
          .span4
            = link_to car_mileages_path(@car), :class => "sb text embossed", :style => "padding-left:14px;" do
              %i.icon-resize-horizontal
              = "Mileages (#{@car.mileages.count})"
        - if @car.user == current_user
          .row-fluid
            .span4
              = link_to new_car_fuel_path(@car), :class => "btn btn-small btn-success" do
                New Fueling
            .span4
              = link_to new_car_service_path(@car), :class => "btn btn-small btn-success" do
                New Service
            .span4
              = link_to new_car_mileages_path(@car), :class => "btn btn-small btn-success" do
                New Mileage
    .pull-left
      %h2= @car.name
      %h4.muted= @car.engine
      %h5.muted= "Last activity about #{time_ago_in_words(@car.updated_at)} ago"
  .row
    #car-description= @car.description
  .row
    .span12
      .pull-right{ :style => "margin-right: 25px;" }
        %strong Convert to:
        .btn-group{ "data-toggle" => "buttons-radio" }
          = link_to reverted_current_currency, "#{car_path(@car)}?currency=#{reverted_current_currency}", :class => "btn btn-info btn-radio"
      #annual
      #car-chart{ :data => { :car =>  car_chart_data(@car, current_currency), :currency => current_currency } }

    %table.table.table-stripped
      %tbody